// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/error-items/[id]" | "/latex-test" | "/login" | "/notebooks" | "/notebooks/[id]" | "/notebooks/[id]/add" | "/practice" | "/print-preview" | "/register" | "/stats" | "/tags"
type AppRouteHandlerRoutes = "/api/admin/migrate-tags" | "/api/admin/system-reset" | "/api/admin/users" | "/api/admin/users/[id]" | "/api/ai/models" | "/api/analytics" | "/api/analyze" | "/api/auth/[...nextauth]" | "/api/error-items" | "/api/error-items/[id]" | "/api/error-items/[id]/delete" | "/api/error-items/[id]/mastery" | "/api/error-items/[id]/notes" | "/api/error-items/batch-delete" | "/api/error-items/clear" | "/api/error-items/list" | "/api/logs/frontend" | "/api/notebooks" | "/api/notebooks/[id]" | "/api/practice/generate" | "/api/practice/record" | "/api/reanswer" | "/api/register" | "/api/register/status" | "/api/settings" | "/api/stats/practice" | "/api/stats/practice/clear" | "/api/tags" | "/api/tags/stats" | "/api/tags/suggestions" | "/api/user" | "/api/videos/search"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/migrate-tags": {}
  "/api/admin/system-reset": {}
  "/api/admin/users": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/ai/models": {}
  "/api/analytics": {}
  "/api/analyze": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/error-items": {}
  "/api/error-items/[id]": { "id": string; }
  "/api/error-items/[id]/delete": { "id": string; }
  "/api/error-items/[id]/mastery": { "id": string; }
  "/api/error-items/[id]/notes": { "id": string; }
  "/api/error-items/batch-delete": {}
  "/api/error-items/clear": {}
  "/api/error-items/list": {}
  "/api/logs/frontend": {}
  "/api/notebooks": {}
  "/api/notebooks/[id]": { "id": string; }
  "/api/practice/generate": {}
  "/api/practice/record": {}
  "/api/reanswer": {}
  "/api/register": {}
  "/api/register/status": {}
  "/api/settings": {}
  "/api/stats/practice": {}
  "/api/stats/practice/clear": {}
  "/api/tags": {}
  "/api/tags/stats": {}
  "/api/tags/suggestions": {}
  "/api/user": {}
  "/api/videos/search": {}
  "/error-items/[id]": { "id": string; }
  "/latex-test": {}
  "/login": {}
  "/notebooks": {}
  "/notebooks/[id]": { "id": string; }
  "/notebooks/[id]/add": { "id": string; }
  "/practice": {}
  "/print-preview": {}
  "/register": {}
  "/stats": {}
  "/tags": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
