// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/error-items/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error-items/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/error-items/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/latex-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/latex-test">> = Specific
  const handler = {} as typeof import("../../../src/app/latex-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notebooks/[id]/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks/[id]/add">> = Specific
  const handler = {} as typeof import("../../../src/app/notebooks/[id]/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notebooks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/notebooks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notebooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notebooks">> = Specific
  const handler = {} as typeof import("../../../src/app/notebooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice">> = Specific
  const handler = {} as typeof import("../../../src/app/practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/print-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/print-preview">> = Specific
  const handler = {} as typeof import("../../../src/app/print-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tags">> = Specific
  const handler = {} as typeof import("../../../src/app/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/migrate-tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migrate-tags">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/migrate-tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/system-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system-reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/system-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/models">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze">> = Specific
  const handler = {} as typeof import("../../../src/app/api/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/error-items/[id]/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-items/[id]/delete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/error-items/[id]/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/error-items/[id]/mastery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-items/[id]/mastery">> = Specific
  const handler = {} as typeof import("../../../src/app/api/error-items/[id]/mastery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/error-items/[id]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-items/[id]/notes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/error-items/[id]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/error-items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-items/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/error-items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/error-items/batch-delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-items/batch-delete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/error-items/batch-delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/error-items/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-items/clear">> = Specific
  const handler = {} as typeof import("../../../src/app/api/error-items/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/error-items/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-items/list">> = Specific
  const handler = {} as typeof import("../../../src/app/api/error-items/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/error-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-items">> = Specific
  const handler = {} as typeof import("../../../src/app/api/error-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/logs/frontend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logs/frontend">> = Specific
  const handler = {} as typeof import("../../../src/app/api/logs/frontend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notebooks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notebooks/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notebooks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notebooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notebooks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notebooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/practice/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/practice/generate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/practice/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/practice/record/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/practice/record">> = Specific
  const handler = {} as typeof import("../../../src/app/api/practice/record/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reanswer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reanswer">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reanswer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/register/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/register/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/register/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stats/practice/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/practice/clear">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stats/practice/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stats/practice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/practice">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stats/practice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tags">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tags/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tags/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tags/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tags/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tags/suggestions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tags/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/videos/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/videos/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/videos/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
